### ISSUE TITLE
Google Logging handler for python

### ISSUE THREAD

**Issue by txomon** [GoogleCloudPlatform/gcloud-python#1824] opened 2016-05-26 15:38 UTC
I found that it would be extremely useful to have a logging sink for python. Maybe this would be more appropriate to have in a side library though.

But the ability to log into the Google Cloud Logging system directly would enable to filter properly from the dashboard, and that would be awesome. Currently the logs are stored in an unknown level and different levels are not recognized.

Example:

https://medium.com/google-cloud/cloud-logging-though-a-python-log-handler-a3fbeaf14704#.mcrqgtkhh

**Comment by dhermes** [comment] 2016-05-26 16:34
Are you asking for something other than http://googlecloudplatform.github.io/gcloud-python/stable/logging-usage.html

**Comment by txomon** [comment] 2016-05-26 17:44
@dhermes That is the reference on the logging interface to Google Cloud logging. I am more referring to having an standard logging handler, as the ones installed in the logging library by default for stderr/stdout:

https://docs.python.org/2/library/logging.html#handler-objects

The article showcased what I meant more specifically.

**Comment by dhermes** [comment] 2016-05-26 17:54
@tseaver Expressed interest in exposing an interface as a standard logger. I'm closing this since it is effectively a duplicate of #1497. We can continue discussion there.

**Closed by dhermes** 2016-05-26 17:54 UTC
Labels: logging
