### ISSUE TITLE
bigquery-usage typos and broken example code.

### ISSUE THREAD

**Issue by DannyLee12** [GoogleCloudPlatform/gcloud-python#2226] opened 2016-08-31 14:42 UTC
Page Name: bigquery-usage
Release: 0.17.0

This page hardly works, there are typos at at least three positions:
`Upload table data from a file:` has two typos, CSV and unmatched parenthesis. The code also doesn't work. Please supply a working template that can be copied and adapted to use. That would be lovely.

**Comment by daspecster** [comment] 2016-08-31 15:19
Thanks for reporting! This is actually a duplicate of #2073.
Somehow I forgot about this. I'll get to work on it right now.

**Comment by daspecster** [comment] 2016-09-02 16:18
I looked [here](http://gcloud-python.readthedocs.io/en/latest/bigquery-usage.html) and also ran `pycodestyle` and `python -m py_compile` on the file those examples are derived from and I couldn't find an issue.

Let me know if I missed the spot you're talking about.

**Closed by daspecster** 2016-09-02 16:18 UTC
Labels: bigquery, docs

**Comment by DannyLee12** [comment] 2016-09-08 09:25
@daspecster This looks good, it seems that either this page has been updated or I was looking an old [page](http://gcloud-python.readthedocs.io/en/0.7.1/bigquery-usage.html). Thanks anyway.
