### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by mbasilyan** [GoogleCloudPlatform/gcloud-python#1552] opened 2016-03-01 01:08 UTC
Page Name: datastore-queries
Release: 0.10.1

This python code (a close copy of one of the pieces in the tutorials), yields an error: 

```python
from gcloud import datastore
ds_client = datastore.Client(project='mikes-playground-project')
#key = client.key('Person')#
#entity = datastore.Entity(key=key)
#entity['name'] = 'Your name'
#entity['age'] = 25
#client.put(entity)
#print("And Out..")
query = datastore.Query('Person')
query.add_filter('age', '<', '100')
list(query.fetch(1), client=ds_client) #even if you remove client=...
```

results in the following error

```
> basilyan@instance-3:~$ python ds.py
> Traceback (most recent call last):
>   File "ds.py", line 12, in <module>
>     query = datastore.Query('Person')
>   File "/usr/local/lib/python2.7/dist-packages/gcloud/datastore/query.py", line 88, in __init__
>     self._project = project or client.project
> AttributeError: 'str' object has no attribute 'project'
```

Using Python 2.7 and gcloud (0.10.1)

**Comment by dhermes** [comment] 2016-03-01 01:17
@mbasilyan Thanks for filing. The issue is that 

```python
query = datastore.Query('Person')
```

should be

```python
query = datastore.Query(kind='Person')
```

Which tutorial are you referring to?

**Comment by dhermes** [comment] 2016-03-01 01:19
Ahhh I found the error. The docs up to `0.10.1` [have the error][1] but it is fixed [in `latest`][2]

[1]: http://googlecloudplatform.github.io/gcloud-python/0.10.1/datastore-queries.html
[2]: http://googlecloudplatform.github.io/gcloud-python/latest/datastore-queries.html

**Comment by dhermes** [comment] 2016-03-01 01:20
Was fixed in #1517.

Thanks for noticing and taking the time to let us know!

**Closed by dhermes** 2016-03-01 01:20 UTC
Labels: datastore, docs

**Comment by mbasilyan** [comment] 2016-03-01 01:23
Thanks @dhermes 

Setting kind='Person' gives me this code:


```
from gcloud import datastore
ds_client = datastore.Client(project='mikes-playground-project')
key = ds_client.key('Person')
entity = datastore.Entity(key=key)
entity['name'] = 'test'
entity['age'] = 25
ds_client.put(entity)
print("And Out..")
query = datastore.Query(kind='Person')
query.add_filter('name', '=', 'test')
x = query.fetch(1)
```

Running it, gives me this error: 

> And Out..
> Traceback (most recent call last):
>   File "ds.py", line 12, in <module>
>     query = datastore.Query(kind='Person')
> TypeError: __init__() takes at least 2 arguments (2 given)
> basilyan@instance-3:~$

**Comment by mbasilyan** [comment] 2016-03-01 01:26
Ahh got it. It's more that it should've been client.query(kind=...) rather than datastore.Client(kind=...)

Fixed it now. Thanks!

```
from gcloud import datastore
ds_client = datastore.Client(project='mikes-playground-project')
key = ds_client.key('Person')
entity = datastore.Entity(key=key)
entity['name'] = 'test'
entity['age'] = 25
ds_client.put(entity)
print("And Out..")
query = ds_client.query(kind='Person')
query.add_filter('name', '=', 'test')
x = query.fetch(1)
```

**Comment by dhermes** [comment] 2016-03-01 01:26
Sorry, my snippet was wrong, but the [`latest` docs][1] are correct:

```python
query = ds_client.query(kind='Person')
```

[1]: http://googlecloudplatform.github.io/gcloud-python/latest/datastore-queries.html

**Comment by dhermes** [comment] 2016-03-01 01:26
Jinx!

**Comment by mbasilyan** [comment] 2016-03-01 01:26
:)
