### ISSUE TITLE
Silent Failure Uploading file to Bucket Configured as a Website

### ISSUE THREAD

**Issue by Zoramite** [GoogleCloudPlatform/gcloud-python#95] opened 2014-05-20 15:24 UTC
Testing uploading a file to a bucket it silently fails if the bucket is configured as a website. Here is the sample code being used:

```py
import gcloud.storage
connection = gcloud.storage.get_connection('project-id', 'email@developer.gserviceaccount.com', 'key-file.key')
bucket = connection.get_bucket('some.website.com')
path = 'answer.html'
file_key = bucket.new_key(path)
file_key.set_contents_from_string('42')
key = bucket.get_key(path)
print key.get_contents_as_string()
```

When I run this against a normal bucket the file is saved and read correctly. When run against a bucket that is configured as a website the upload silently fails and is unable to retrieve the value from the bucket to print.

**Comment by dhermes** [comment] 2015-01-27 05:34
Closing this out since we could not reproduce.

@gsalgado Please re-open if you are still having this issue.

**Closed by dhermes** 2015-01-27 05:34 UTC
Labels: bug, storage
