### ISSUE TITLE
Python documentation missing examples, etc

### ISSUE THREAD

**Issue by danielecook** [GoogleCloudPlatform/gcloud-python#2037] opened 2016-07-30 14:50 UTC
It seems to have disappeared:

https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/datastore/client/client

**Comment by dhermes** [comment] 2016-07-30 16:08
@danielecook How do you mean disappeared? They are different from the previous Sphinx docs, but the Sphinx docs are still up at http://gcloud-python.readthedocs.io/en/latest/

Maybe @daspecster can comment about the differences?

**Comment by danielecook** [comment] 2016-07-30 17:01
Look at the content on that link I provided. There are no examples. There are no descriptions. This was not the case previously. Compare with the ruby language page. When I google 'gcloud-python' the first result is the link above - not the sphinx docs you provided. Why does documentation exist in multiple places? Thanks!

**Comment by jgeewax** [comment] 2016-07-30 21:19
@daspecster : I thought that we fixed this so the examples were still there... If not, can we... fix it?

**Comment by daspecster** [comment] 2016-07-30 21:27
Hey! So we're not pulling in the RST files and we have some examples in those.

I will have to check it out, but either we need to parse those usage RST files and find a place to put them in the doc site or we should move those over into the appropriate module doc strings. I think the latter would be the quickest.

The tricky part is going to be deciding where to put things in the new doc site.

**Comment by daspecster** [comment] 2016-07-30 21:39
Actually I take that back, 
The corresponding example mentioned above would be here http://gcloud-python.readthedocs.io/en/latest/datastore-client.html which has some example code in it.  So this could really be a bug, I'll check it out. If the examples are literalincludes then yeah I don't have that built into the generator.

**Comment by danielecook** [comment] 2016-08-01 02:50
Thanks!

**Comment by jgeewax** [comment] 2016-08-01 11:38
OK -- so long as we get snippets back. That is an absolute requirement here....

**Comment by tswast** [comment] 2016-08-09 20:10
From the bug #2072 I closed as a duplicate of this one:

Compare http://googlecloudplatform.github.io/gcloud-python/0.17.0/bigquery-client.html and http://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/bigquery/client/client

There is a ton of information missing now. For example, I don't see any information about what parameters the constructor takes.

Also, the links to the "Using the API" pages have completely disappeared.

**Comment by daspecster** [comment] 2016-08-15 14:47
Sorry, I just got back in the US where the internet works most of the time haha.
@tswast thanks for the link, I'll see about the params as well.

**Closed** 2016-08-17 20:30 UTC
Labels: bug, docs
