### ISSUE TITLE
Dataset isn't in the docs as a "concept"

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#708] opened 2015-03-12 11:13 UTC
We added back the Dataset class (basically an alias class that fills in some blanks for you), but it's not listed on the left navigation of the docs. Any chance we can put that back?

If we do, we should add a lovely `..note:` banner on that page saying that if you only interact with one dataset (a default one) that you don't need to worry about this, and you can use `datastore.<method>` and we'll automatically use the default dataset.

**Comment by dhermes** [comment] 2015-03-12 18:17
Closing as a duplicate of #707 (I started commenting there before I realized this existed).

**Closed by dhermes** 2015-03-12 18:17 UTC
Labels: datastore, docs
