### ISSUE TITLE
upload file to cloud storage stuck randomly

### ISSUE THREAD

**Issue by matrixl** [GoogleCloudPlatform/gcloud-python#1563] opened 2016-03-03 16:02 UTC
My program will stuck randomly when call blob.upload_from_filename function, most of the time it happend to a pdf file (it also happened to small size pdf file). with version 0.10.1

client = storage.Client.from_service_account_json(app.config["GCS_KEYFILE"], app.config["GCS_PROJECTID"])
bucket = client.get_bucket(app.config["GCS_BUCKETID"])
blob = bucket.blob(remote_path)
_**blob.upload_from_filename(filename=local_path)**_

**Comment by dhermes** [comment] 2016-03-03 16:06
Are you using a threaded environment? Have you killed the process every time or waited for a stacktrace?

**Comment by matrixl** [comment] 2016-03-03 16:13
It's a python flask application, so it is a threaded environment. the program will wait for a stacktrace.

**Comment by dhermes** [comment] 2016-03-03 16:21
I've experienced this before. `httplib2` is not threadsafe and I've been able to reproduce long waits before a strange SSL error (due to threads getting crossed).

Your easiest solution for now is just to create a Client / Connection as a thread local. @jonparrott has been working to make this easier though for the long term

**Comment by matrixl** [comment] 2016-03-03 17:14
Great, thanks for your help!

**Comment by dhermes** [comment] 2016-03-03 17:16
I'm going to close this and just point to #1214. Thanks for reporting, it's good to get a sense of priorities.

If it turns out that this wasn't the issue, ping this issue and we can re-open and discuss.

**Closed by dhermes** 2016-03-03 17:16 UTC
Labels: bug, storage
