### ISSUE TITLE
DISCUSSION: Entity still not behaving like a dict

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/gcloud-python#620] opened 2015-02-12 19:42 UTC
Since you are (optionally) associating Entities with Keys on instantiation, and since Entity inherits from dict I think it's reasonable to assume that all of the following would work. 

```
ent1 = Entity(key=key1)
ent2 = Entity(key=key2)
assert not dict(ent1) == dict(ent2)

ent = Entity()
assert not 'key' in ent
ent['key'] = Key('Kind', 'id')
datastore.put(ent)

props={'prop1': 'value1', 'prop2':'value2'}
ent = Entity(key=key1, **props)
```

That said I'm still of the opinion that Entity should not be necessary as a class, using instead `datastore.put(key, dict, **options)` or, Entity should be completely key agnostic making implementation of the above easier.

**Comment by dhermes** [comment] 2015-02-12 19:47
1.  `dict(ent1) == dict(ent2)` is and has been supported.
1.  We can't support

    ```python
    ent['key'] = Key('Kind', 'id')
    ```
    because `key` is a valid property name. (`__key__` is what would do this, but `__*__` properties [can't][1] be set by users).
1.  I'm a fan of `ent = Entity(key=key1, **props)`, it just isn't pressing given the ease of

    ```python
    ent = Entity(key=key1)
    ent.update(props)  # or ent.update(**props)
    ```

[1]: https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/21e029b2657ebb15fef5429c90c4315326855fd1/proto/datastore_v1.proto#L151-L155

**Comment by elibixby** [comment] 2015-02-12 19:59
RE: 2, From https://cloud.google.com/appengine/docs/python/datastore/entities

> Don't name a property "key." This name is reserved for a special property used to store the Model key. > Though it may work locally, a property named "key" will prevent deployment to App Engine.

We should not be encouraging or possibly even allowing it. I think a good way to do that would be overwrite with the required key property.

**Comment by dhermes** [comment] 2015-02-12 20:06
@elibixby #532 is a discussion about things like that (things we shouldn't encourage users to do).

Thanks for the quote about App Engine. I was actually trying to find that in the proto spec.

By swapping for the constructor like a dict, we exchange

```python
ent = Entity(..., exclude_from_indexes=...)
ent.update(**props)
```

for

```python
ent = Entity(**props)
ent.set_exclude_from_indexes(...)
```

There is no silver bullet here.

**Comment by elibixby** [comment] 2015-02-12 20:21
Except that if we have key specified within props:
```
props={'key':datastore.Key('kind',1), 'prop1':'value1'}
ent = Entity(**props)
```
is decidedly cleaner and more dict-like than `ent = Entity(key=Key('kind',1), **props)`

Also I prefer setting exclude from indexes outside the constructor properties have been specified because it allows you to check that the property you which to exclude is actually in the entity, e.g.:

```
ent = Entity(**props)
if 'title' in ent:
    ent.exclude_from_indexes('title')
```
Although I don't really think it's actually a problem on the protobuf side of things (i'd have to double check), it certainly makes feel as a backend-naive developer feel safer =).

**Comment by elibixby** [comment] 2015-02-12 20:28
I just tested (1), and it failed. Two `Entity`s with different keys but the same properties test as equal when converted to `dict`s

**Comment by tseaver** [comment] 2015-02-12 21:40
@elibixby I'm puzzled:  why would you expect that converting to `dict` didn't change the semantics?  That coercion is lossy.  By design, the key is not a "property" (an entry in the Entity's items), but a special attribute on the side.

**Comment by elibixby** [comment] 2015-02-12 22:21
Right, this is the design I'm questioning. I expected it to fail, I'm arguing that more intuitive usage would be for it to succeed.

**Comment by elibixby** [comment] 2015-02-12 22:27
To expand on this: 

If Key is not included in the dict backing entity should not BE a dict, but HAVE a dict. When extending a base data structure I tend to think only of adding behavior/restrictions, not storing additional data outside that data structure. 

However, since having Entity be a subclass of dict has already been discussed to death, and we are sticking with it, I think that Key SHOULD be a part of the entity backing dict, to be in accordance with the design principles in the first paragraph.

**Comment by jgeewax** [comment] 2015-02-13 14:32
This is a tricky one... Just wanted to add a couple thoughts:

Let's assume the following...

```python
entity = Entity(key=same_key)
same_entity = Entity(key=same_key)
other_entity = Entity(key=other_key)
```

Some equality checks (`==` means -- IMO -- "same data, same key")

```python
# Object == means "same data, same key"
>>> entity == other_entity
False
>>> entity == same_entity
True

# dict() == means "same data, key doesn't matter"
>>> dict(entity) == dict(other_entity)  # {} == {}
True
>>> dict(entity) == dict(same_entity)  # {} == {}

# .key() == means "same key, data doesn't matter"
>>> entity.key() == other_entity.key()
False
>>> entity.key() == same_entity.key()
True
```

Make `same_entity` have different data:

```python
>>> same_entity['name'] = 'Danny'
```

Some more equality tests:

```python
>>> entity == same_entity
False
>>> entity.key() == same_entity.key()
True
>>> dict(entity) == dict(same_entity)  # {} == {'name': 'Danny'}
False
```

---

As for the `key` stuff, I personally think `'key'` should be treated as any other property:

```python
>>> entity1['key'] = 'Whatever string I feel like...'
>>> entity1.key() == entity1['key']
False
```

App Engine says not to do this, but (if I recall correctly) that's due to both `ext.db` and `ext.ndb` using an ORM style way of specifying properties (where property names are not accessed by using their string name, but instead are Python instance properties on the object).

This makes one weird case:

```python
>>> properties = {'key': 'My key property'}
>>> entity = Entity(key=Key(...), **properties)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type object got multiple values for keyword argument 'key'
```

The easy fix is...

```python
>>> properties = {'key': 'My key property'}
>>> entity = Entity(key=Key(...))
>>> entity.update(properties)
```

Another option is to make it so that `Entity` doesn't take keyword arguments, but instead takes a dictionary of data to start, meaning the following would work exactly as expected:

```python
>>> entity = Entity(key=Key(...), {'key': 'My key property'})
```

It breaks the `dict` constructor keyword argument assignment, but I'm not horrified by that, as you can still do `.update(key=value, key2=value)` and get the result you want...

---

Regarding `Entity` not needing to exist as a class -- I can't say I'm against that idea... I'd need to do a lot more thinking, but it's a great point... Maybe @dhermes has some input here.

/cc @pcostell on ... all of this...

**Comment by jgeewax** [comment] 2015-02-13 16:43
I also forgot, if you want the `prop=value` style syntax on the constructor, you could do:

```python
>>> entity = Entity(key=Key(...), dict(key=value, key2=value, name='Danny'))
```

**Comment by elibixby** [comment] 2015-02-13 17:56
Yeah, I understand the equality testing behavior you want, and it is coherent and makes sense, but IMO that behavior shouldn't be implemented by subclassing dict. It seems like a nice syntactic shortcut, but I think it is conceptually misleading, because you are really just using the backing dict as a stored element.

**Comment by dhermes** [comment] 2015-02-13 18:09
@jgeewax I updated the post for you, we ditched the `ent.key()` style and now it's just a property.

--------

RE: `db`...who knows. RE: `ndb`, if a property has the name `key`, the object key is still available as `_key`. The constructor takes `__init__(*args, **kwargs)` so people can even use `self` as a property name if they like.

--------

As for dropping `Entity`, I am for it in theory but keep getting hung up on the indexes. At the end of the day, it just isn't worth trying to get rid of it. This is something more fit for an ORM.

--------

We've heard no other feedback about issues or confusions with subclassing dict. It seems there have been a fair amount of people trying the library out (JJ's original design subclassed `dict`):

```
$ vanity gcloud
  gcloud-0.01.tar.gz    2014-01-28         1116
  gcloud-0.02.tar.gz    2014-01-28         1106
gcloud-0.02.1.tar.gz    2014-01-28         1130
gcloud-0.02.2.tar.gz    2014-02-20         2349
 gcloud-0.3.0.tar.gz    2014-11-26         1316
-----------------------------------------------
gcloud has been downloaded 7017 times!
```

The `__getitem__` syntax (i.e. `ent['propName']) and the `__getattr__` syntax (i.e. `ent.actual_prop`) are distinct and don't seem to cause confusion.

**Comment by elibixby** [comment] 2015-02-13 18:09
To add more of a user perspective to this, as a naive user I say:
> Oh! this class subclasses dict! that means I can do things like: parse it into json, use dict pretty printers, get an item iterator etc... and I expect all of those things to access all of the data associated with this object, even if it doesn't preserve the objects behavior or structure.

Then I do that, and suddenly I have a bunch of (json objects | strings | iterators | etc) which no longer have any reference to the key, and as such are pretty useless. 

Now I realize this is an easy work around (`a = dict(ent), a.update(ent.key()), process(a)`) and it's easy to realize that this is a workaround that needs to be made, by looking a little bit more in depth at the code, but the idea of an idiomatic library (IMO) is that this shouldn't be necessary. If it subclasses dict, it should behave like a dict++.

**Comment by elibixby** [comment] 2015-02-13 18:17
If not dropping `Entity` all together, what about making it `key` naive? Then `datastore.put` simply takes an `Entity` which is really a real dict with an index, and a `Key`

**Comment by pcostell** [comment] 2015-02-13 22:44
In terms of making `key` just another property, it should likely be called `__key__`. This makes it consistent with querying (i.e. `SELECT __key__ FROM Kind`), however it somewhat clashes with python naming rules. In terms of the datastore restriction that names with `__*__` aren't allowed, this would be ok since gcloud would convert entity['__key__'] = x -> entity with a key equal to x. _However_ key is an immutable property for Entities. So the user shouldn't ever be allowed to write entity['__key__'] = x. Perhaps you could allow it as a read only property though, which could let you support dict(entity) that includes the key.

At one point there was a proposal to wrap values with necessary indexing data. Then each individual value stores its own index information and it doesn't need to be stored on the entity.

**Comment by jgeewax** [comment] 2015-02-13 22:52
@pcostell : I think assigning `key` should be allowed so that you can effectively "copy" the data from one entity to another.... For example:

```python
entity = get_entity_somehow()

# "Copy" the data to another entity:
entity.key = Key('OtherKind', 'my-key-name')
entity.put()
```

Is that crazy?

---

I was also saying that `key` should be allowed as a name for something to store *not* the actual `Key`. That is... `entity['key'] = True` should be allowed, and datastore would just treat `key` as though it was any other property like `enabled`... 

If you want to set the entity's `Key` (do it with `Entity(key=Key(...))` or `entity.key = Key(...)` (not `entity['key'] = ...` which sets a property called key rather than the entity's key).

**Comment by dhermes** [comment] 2015-02-13 22:58
I'm having strong feelings of "if it ain't broke, don't fix it" right now. It already does what most people say they think it should do.

@pcostell proposal is a hack to get the dictionary only approach working, but (correct me if I'm wrong Patrick) I don't think it's an endorsement of that approach.

There is no fundamental reason for dictionary only, other than making Python and JSON play happy together (which is not idiomatic Python FWIW).

The separation of data (via `__getitem__`), "address" (via `key`) and metadata (via `exclude_from_indexes`) is isomorphic to any other minimal formulation of the abstraction.

**Comment by pcostell** [comment] 2015-02-13 23:04
@jgeewax I think assigning to the key could get dangerous. In particular it gives the illusion that the data can move. Based on your code snippet I would expect that to move the entity to a different key, not make a copy. If you want a copy, I would instead prefer something like:

     entity = get_entity_somehow()
     e = Entity(key=a_new_key)
     e.populate(entity)

(Or something to that effect, I don't care how the properties get into the entity).

@dhermes Yes my proposal is just a way to get the dictionary approach.

Also I agree that `key` should be an allowable property name that is distinct from the entity's `__key__`. `ndb` accomplishes this in a strange way. You can have a property named key but you can't populate it in
constructor like all your other property values since key in the constructor is reserved for the entity's key.

**Comment by elibixby** [comment] 2015-02-14 20:22
@pcostell @jgeewax I think the copying example is really good demonstration of how I think things feel counter-intuitive right now. FWIW I think this is another place where a `Key` naive `Entity` shines. Then you can have a property named key, AND use `**props` syntax. Something like:

```
entity = Entity(**props, bonus_prop='value!')
entity.exclude_from_indexes(*a_list_of_keys) //warns on keys in this list, not on entity
datastore.put(key, entity)
```

Then copying is as simple as 
```
datastore.put(key, entity)
datastore.put(some_other_key, entity)
```

The only downside is that batch `put`s become a little trickier. But `datastore.put(key1, entity1, key2, entity2, ... )` isn't too bad.

**Comment by jgeewax** [comment] 2015-02-15 18:41
Or (if we're going this route), for batch puts we could use a dictionary, or a set of tuples:

```python
datastore.put({
  key1: entity1,
  key2: entity2
})
```

or

```python
datastore.put(
  (key1, entity1),
  (key2, entity2)
)
```

The big change that this represents though is that we're sort of treating datastore a bit like a key-value store here, right? (ie, this API for get/set feels a bit like memcache...)

**Comment by elibixby** [comment] 2015-02-15 18:58
I really like this. I was going to say  `Key` could be made hashable, and then use them as keys in a  `dict`. Didn't know if that was a little too out there. 

At that point `datastore` and `dict` have more or less identical method signatures, although different syntax. 

Interesting.

**Comment by tseaver** [comment] 2015-02-15 19:06
FWIW, as of #619 (merged), `Key` instances are hashable (they support both `__eq__` and `__hash__`).  Incomplete keys won't compare equal to anything but themselves.

**Comment by dhermes** [comment] 2015-06-18 23:09
I'm closing this out as the discussion went dead.

Reviewing it, I think one thing a native developer might expect to work would be `json.dumps` to include all values. Currently it does not:

```python
>>> e = Entity(key=Key('Foo', 'bar'))
>>> e['prop'] = 'val'
>>> json.dumps(e)
'{"prop": "val"}'
```

We could open a **new** bug and discuss `to_json` and `from_json` methods, but I'd wager most people will want to write their own layer on top (#557 also makes this a bit murkier to discuss).

**Closed by dhermes** 2015-06-18 23:09 UTC
