### ISSUE TITLE
There are broken links for source code

### ISSUE THREAD

**Issue by edgartanaka** [GoogleCloudPlatform/gcloud-python#2104] opened 2016-08-16 17:51 UTC
Broken links here http://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/storage/client/client 
when clicking to see source code

**Comment by daspecster** [comment] 2016-08-16 18:01
Thanks for reporting!
This is a duplicate of #2046, and will be fixed by #2052.

**Comment by daspecster** [comment] 2016-08-16 18:06
Actually I'll leave this open and have the PR close it when it's merged. My bad!

**Comment by daspecster** [comment] 2016-08-17 15:55
Should be fixed with the next docs generation per #2052.

**Closed by daspecster** 2016-08-17 15:55 UTC
Labels: docs
