### ISSUE TITLE
Support bulk operations in bigtable

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/gcloud-python#1953] opened 2016-07-01 22:05 UTC
I would like to be able to write many rows at once in a sample. I searched for `MutateRowsRequest` from the proto, but don't see any references to it in the code.

**Comment by tseaver** [comment] 2016-07-01 22:19
Thanks for the report!  Duplicate of #1546.

**Closed by tseaver** 2016-07-01 22:19 UTC
Labels: bigtable
